// The plugin's supported root surface, mirrored here so `withFluid` can refuse to
// group a class whose root the plugin never emits (`fl-opacity-50/75`,
// `fl-widget-a/b`). Grouping an unsupported root would delete a real fallback (the
// class it displaces) even though the fluid class compiles to nothing — the same
// rendered-CSS correctness risk `withFluid` exists to prevent.
//
// GENERATED / KEPT IN SYNC: each entry is a plugin root from `fluid-tailwind`'s
// `src/roots.ts` with the leading `fl-` stripped (the core-equivalent root that
// `analyzeFluid` derives). The plugin package holds a `roots-sync` test that imports
// `ROOTS` and this set and fails CI on any drift, so adding a root there without
// updating this list can't ship silently. Regenerate with the same strip-and-sort:
//   new Set(ROOTS.map((r) => r.root.replace(/^fl-/, '')))

/** Core-equivalent roots the plugin supports (leading `fl-` stripped). */
export const FLUID_ROOTS: ReadonlySet<string> = new Set([
	'basis',
	'border',
	'border-b',
	'border-e',
	'border-l',
	'border-r',
	'border-s',
	'border-t',
	'border-x',
	'border-y',
	'bottom',
	'end',
	'gap',
	'gap-x',
	'gap-y',
	'h',
	'indent',
	'inset',
	'inset-x',
	'inset-y',
	'leading',
	'left',
	'm',
	'max-h',
	'max-w',
	'mb',
	'me',
	'min-h',
	'min-w',
	'ml',
	'mr',
	'ms',
	'mt',
	'mx',
	'my',
	'outline',
	'outline-offset',
	'p',
	'pb',
	'pe',
	'pl',
	'pr',
	'ps',
	'pt',
	'px',
	'py',
	'right',
	'ring',
	'rounded',
	'rounded-b',
	'rounded-bl',
	'rounded-br',
	'rounded-e',
	'rounded-ee',
	'rounded-es',
	'rounded-l',
	'rounded-r',
	'rounded-s',
	'rounded-se',
	'rounded-ss',
	'rounded-t',
	'rounded-tl',
	'rounded-tr',
	'scroll-m',
	'scroll-mb',
	'scroll-me',
	'scroll-ml',
	'scroll-mr',
	'scroll-ms',
	'scroll-mt',
	'scroll-mx',
	'scroll-my',
	'scroll-p',
	'scroll-pb',
	'scroll-pe',
	'scroll-pl',
	'scroll-pr',
	'scroll-ps',
	'scroll-pt',
	'scroll-px',
	'scroll-py',
	'size',
	'space-x',
	'space-y',
	'start',
	'stroke',
	'text',
	'top',
	'tracking',
	'translate-x',
	'translate-y',
	'w',
]);
